Repository YouAndMyFuBao/fubao-client, pull requests merged in 2023-12, with the labels that each got.

#7 [DOCS] pr 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#8 [FEAT] Layout 컴포넌트 구현
  .pnp.cjs
  package.json
  src/components/layout/index.ts
  src/components/layout/layout.css.ts
  src/components/layout/layout.tsx
  src/pages/_app.tsx
  src/styles/globals.css
  yarn.lock
Labels: enhancement

#11 [FEAT] Home 화면 기능 구현
  .pnp.cjs
  package.json
  public/assets/svgs/IconArrowBack.svg
  public/assets/svgs/IconHamburger.svg
  public/assets/svgs/IconNavigationButton.svg
  public/assets/svgs/index.ts
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  src/components/layout/layout.css.ts
  src/components/navigation-modal/navigation-modal.css.ts
  src/components/navigation-modal/navigation-modal.tsx
  src/pages/home/[_components]/home-header.css.ts
  src/pages/home/[_components]/home-header.tsx
  src/pages/home/index.tsx
  src/styles/reset.css
  yarn.lock
Labels: enhancement

#13 [FEAT] 카카오 간편 로그인 기능 구현
  .pnp.cjs
  package.json
  src/apis/baseAxios.ts
  src/apis/postLogin.ts
  src/pages/api/hello.ts
  src/pages/home/_components/home-header.css.ts
  src/pages/home/_components/home-header.tsx
  src/pages/home/index.tsx
  src/pages/kakao/index.tsx
  src/pages/redirect/index.tsx
  yarn.lock
Labels: enhancement

#14 [FEAT] 편지쓰기 화면 구현
  src/hooks/useLetterContext.tsx
  src/pages/_app.tsx
  src/pages/letter/create-letter/index.css.ts
  src/pages/letter/create-letter/index.tsx
  src/pages/letter/index.tsx
  src/pages/letter/preview-letter/index.css.tsx
  src/pages/letter/preview-letter/index.tsx
Labels: enhancement

#16 [CHORE] 스타일링 패키지 변경
  .pnp.cjs
  next.config.js
  package.json
  src/components/layout/layout.css.ts
  src/components/layout/layout.tsx
  src/components/navigation-modal/navigation-modal.css.ts
  src/components/navigation-modal/navigation-modal.tsx
  src/pages/_app.tsx
  src/pages/home/[_components]/home-header.css.ts
  src/pages/home/[_components]/home-header.tsx
  src/pages/home/_components/home-header.css.ts
  src/pages/home/_components/home-header.tsx
  src/pages/letter/create-letter/index.css.ts
  src/pages/letter/create-letter/index.tsx
  src/pages/letter/preview-letter/index.css.tsx
  src/pages/letter/preview-letter/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/globals.css
  src/styles/reset.css
  tsconfig.json
  yarn.lock
Labels: settings

#20 [FIX] Navigation Modal 미완성 기능 구현
  .pnp.cjs
  src/components/layout/layout.css.ts
  src/components/navigation-modal/navigation-modal.css.ts
  src/components/navigation-modal/navigation-modal.tsx
  src/pages/home/[_components]/home-header.css.ts
  src/pages/home/[_components]/home-header.tsx
  src/pages/home/_components/home-header.css.ts
  src/pages/home/_components/home-header.tsx
  src/styles/GlobalStyle.tsx
Labels: bug

#22 [FEAT] 모달 컴포넌트 생성 및 storybook 테스트 작성
  .pnp.cjs
  .storybook/main.ts
  package.json
  src/components/modal/modal.css.ts
  src/components/modal/modal.tsx
  src/stories/Modal.stories.ts
  yarn.lock
Labels: enhancement

#24 [FEAT] Button 컴포넌트 생성
  .pnp.cjs
  .storybook/preview.tsx
  package.json
  src/components/button/button.css.ts
  src/components/button/button.stories.ts
  src/components/button/button.tsx
  src/components/button/index.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  yarn.lock
Labels: enhancement

#26 [FEAT] Header 컴포넌트 생성
  .storybook/main.ts
  next.config.js
  public/assets/svgs/IconKaKao.svg
  public/assets/svgs/index.ts
  src/components/bottomSheet/bottomSheet.css.ts
  src/components/bottomSheet/bottomSheet.stories.ts
  src/components/bottomSheet/bottomSheet.tsx
  src/components/button/button.css.ts
  src/components/button/button.tsx
  src/components/header/header.css.ts
  src/components/header/header.stories.ts
  src/components/header/header.tsx
  src/components/modal/modal.tsx
  src/pages/letter/create-letter/index.tsx
  src/stories/Configure.mdx
  src/stories/Modal.stories.ts
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/utils/textLineBreak.tsx
Labels: enhancement

#29 [ENV] 글꼴 설정
  public/fonts/PretendardVariable.woff2
  public/fonts/UhBeeKang-Ja.woff
  public/fonts/fonts.ts
  src/components/layout/layout.tsx
Labels: enhancement

#31 [FEAT] Snackbar 공통 컴포넌트 구현
  src/components/snackbar/snackbar.css.ts
  src/components/snackbar/snackbar.stories.ts
  src/components/snackbar/snackbar.tsx
Labels: enhancement

#34 [FEAT] 푸바오 우체통 기능 구현
  .pnp.cjs
  package.json
  public/assets/img/fubao.jpeg
  public/assets/svgs/IconCreatedAt.svg
  public/assets/svgs/IconPostBox.svg
  src/apis/getPostBox.ts
  src/data/type.ts
  src/hooks/useIntersect.ts
  src/pages/_app.tsx
  src/pages/post-box/_components/created-at-tag.css.ts
  src/pages/post-box/_components/created-at-tag.tsx
  src/pages/post-box/_components/post.css.ts
  src/pages/post-box/_components/post.tsx
  src/pages/post-box/index.tsx
  src/pages/post-box/post-box.css.ts
  yarn.lock
Labels: enhancement

#35 [FEAT] 홈 > 하트 채우기 기능 구현
  .pnp.cjs
  package.json
  src/apis/getPostBox.ts
  src/apis/postLogin.ts
  src/components/navigation-modal/navigation-modal.css.ts
  src/components/navigation-modal/navigation-modal.tsx
  src/pages/home/_components/home-message-bottom.css.ts
  src/pages/home/_components/home-message-bottom.tsx
  src/pages/home/_components/home-message.css.ts
  src/pages/home/_components/home-message.tsx
  src/pages/home/_components/my-letter-button.css.ts
  src/pages/home/_components/my-letter-button.tsx
  src/pages/home/_components/scratchable-image.css.ts
  src/pages/home/_components/scratchable-image.tsx
  src/pages/home/index.tsx
  src/pages/post-box/index.tsx
  yarn.lock
Labels: enhancement

#37 [FEAT] 로그아웃, 회원탈퇴 기능 구현
  src/apis/baseAxios.ts
  src/apis/deleteDeactivation.ts
  src/apis/postLogin.ts
  src/apis/postLogout.ts
  src/components/navigation-modal/navigation-modal.css.ts
  src/components/navigation-modal/navigation-modal.tsx
  src/data/type.ts
  src/pages/redirect/index.tsx
  src/styles/GlobalStyle.tsx
Labels: enhancement

#39 [FEAT] 링크 복사하기 공통 컴포넌트 구현
  public/assets/svgs/IconLink.svg
  public/assets/svgs/index.ts
  src/components/copy-link/copy-link.css.ts
  src/components/copy-link/copy-link.stories.ts
  src/components/copy-link/copy-link.tsx
  src/components/snackbar/snackbar.tsx
Labels: enhancement

#40 [FIX] Button 컴포넌트 수정
  src/components/button-group/button-group.css.ts
  src/components/button-group/button-group.stories.ts
  src/components/button-group/button-group.tsx
  src/components/button/button.css.ts
  src/components/button/button.stories.ts
  src/components/button/button.tsx
Labels: enhancement
